version: '3.6'

services:
  drupal7:
    image: drupal:7-apache
    ports:
      - 8080:80
    volumes:
      - ./apache:/etc/apache2/sites-available
      - ./drupal7:/var/www/html
      - ./bash-scripts/drupal7.sh:/var/install_drupal7.sh
    environment:
      - MYSQL_HOST=mysql7
      - MYSQL_DATABASE=drupal7
      - MYSQL_USER=drupal7
      - MYSQL_PASSWORD=drupal7
    depends_on:
      - mysql7

  mysql7:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql7:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=drupal7
      - MYSQL_USER=drupal7
      - MYSQL_PASSWORD=drupal7
      - MYSQL_ROOT_PASSWORD=root

  portainer-agent:
    image: portainer/agent
    environment:
      - AGENT_CLUSTER_ADDR=tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data

volumes:
  portainer_data: